config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    collection do
      post 'save_query'
      get 'analytics'
    end
  end

  # route /analytics to /articles/analytics
  get 'analytics', to: redirect('/articles/analytics')
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "articles#index", as: :authenticated_root
  # unauth root to be /users/sign_in
  root "devise/sessions#new", as: :unauthenticated_root
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

    # include Elasticsearch::Model
    # include Elasticsearch::Model::Callbacks

    # regenerating elasticsearch index for docs after updating or deleting
    # after_commit on: [:create, :update] do
    #     __elasticsearch__.index_document
    # end

    # this is a third party gem that allows us to search using elasticsearch
    # searchkick

    # def search_data
    #     {
    #         title: title,
    #         body: body
    #     }
    # end
end


# Index creation right at import time is not encouraged.
# Typically, you would call create_index! asynchronously (e.g. in a cron job)
# However, I am adding it here so that this usage example can run correctly.
# Article.__elasticsearch__.create_index!
# Article.import

# @articles = Article.search('foobar').records

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def email_required?
    false
  end
end

app/models/user_query.rb
class UserQuery < ApplicationRecord
  belongs_to :user
  validates :query, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    protect_from_forgery with: :exception
    before_action :update_allowed_parameters, if: :devise_controller?

    def after_sign_in_path_for(_resource)
        authenticated_root_path
    end

    def after_sign_out_path_for(_resource)
        unauthenticated_root_path
    end

    protected

    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password) }
        devise_parameter_sanitizer.permit(:account_update) do |u|
        u.permit(:username, :email, :password, :current_password)
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show]

  # GET /articles or /articles.json
  def index
    search_term = params[:term].present? ? params[:term] : nil

    # Save the current query to the database after a debounce
    @debounced_query = debounce(1000) { search_term }

    if @debounced_query
      UserQuery.create(query: @debounced_query, user: current_user)
      # dev logging 😅
      puts "Query saved: #{@debounced_query} ✅✅✅✅✅✅✅✅"
      update_previous_queries(@debounced_query)
    end

    @articles = []

    if @debounced_query
      @articles = Article.where("title LIKE ?", "%#{@debounced_query}%")
      @articles = @articles + Article.where("body LIKE ?", "%#{@debounced_query}%")
    else
      @articles = Article.all
    end

    respond_to do |format|
      format.js   # js formatting
      format.html
    end
  end

  # display the query analytics
  def analytics
    puts "Current user: #{current_user.email}"
    # select all queries from the current user
    @user_queries = UserQuery.where(user: current_user)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      # elastic search document reindexing
      # article = Article.last
      # article.reindex
      
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    # Use require and permit to whitelist the allowed attributes
    params.require(:article).permit(:title, :body)
  end

  # Debounce function to prevent saving the same query multiple times
  def debounce(time)
    return if time.nil?

    current_time = Time.now.to_f
    @last_called ||= 0.0

    if current_time - @last_called >= time / 1000.0
      @last_called = current_time
      yield
    end
  end

  def update_previous_queries(new_query)
    return unless new_query

    previous_queries = UserQuery.where.not(id: nil)
    found_matches = 0
    previous_queries.each do |query|
      # delete extra matches if more than 1 exact match is found
      if query.query == new_query
        found_matches += 1
        if found_matches > 1
          query.destroy
          # dev logging 😅
          puts "Query deleted: #{query.query} ❌❌❌❌❌❌❌❌"
        end
      # delete previous queries if the new query is more complete 
      elsif new_query.include?(query.query)
        # If the new query is more complete, delete the previous query
        query.destroy
        # dev logging 😅
        puts "Query deleted: #{query.query} ❌❌❌❌❌❌❌❌"
      elsif query.query.include?(new_query)
        # If the previous query is more complete, stop the loop
        return
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= link_to article do %>
  <div id="<%= dom_id article %>" class="article">
    <h5 class="title">
      <%= truncate(article.title, length: 30, omission: '...') %>
    </h5>
    <p class="body">
      <%= truncate(article.body, length: 100, omission: '...') %>
    </p>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_search_results.html.erb
<%
=begin%>
 <% if @articles.present? %>
  <ul>
    <% @articles.each do |article| %>
      <li><%= link_to article.title, article %></li>
    <% end %>
  </ul>
<% else %>
  <p>No articles found</p>
<% end %> 
<%
=end%>

<% @articles.each do |article| %>
  <%= render article %>
  <p>
    <%= link_to "Show this article", article %>
  </p>
<% end %>

app/views/articles/analytics.html.erb
<div id='analytics'>
  <h1>User Queries Analytics</h1>
  <% if @user_queries.present? %>
    <ul>
      <% @user_queries.each do |query| %>
        <li>↪ <%= query.query %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No user queries available.</p>
  <% end %>

</div>

<%= link_to "Back to articles", articles_path, class: 'neutral' %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'search' %>
<% end %>

<p style="color: green"><%= notice %></p>

<%= form_tag articles_path, method: :get, remote: true do %>
  <%= text_field_tag :term, params[:term], placeholder: "Search articles", id: "search_term" %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<div id="articles">
  <% if @articles.any? %>
    <%= render @articles %>
  <% else %>
    <span>No articles found</span>
  <% end %>
</div>

app/views/articles/new.html.erb
<div id='new-article'>
  <h1>New article</h1>

  <%= render "form", article: @article %>

  <br>

  <div>
    <%= link_to "Back to articles", articles_path, class: 'neutral' %>
  </div>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<div id='single_article'>
  <div class="article">
    <h5 class="title">
      <%= @article.title %>
    </h5>
    <p class="body">
      <%= @article.body %>
    </p>
  </div>

  <div>
    <%= link_to "Back to articles", articles_path, class: 'neutral' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= stylesheet_link_tag 'search' %>

    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    <%= yield :head %>
  </head>

  <body>
    <h1>SearchEngine</h1>
    <% if user_signed_in? %>
      <header>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "danger" %>
        <%= button_to "Analytics", '/analytics', method: :get, class: "safe"  %>
        <%= link_to "New article", new_article_path, class: "safe" %>
      </header>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>